#!/bin/bash

mv xaa affectedGeneList.1.txt
mv xab affectedGeneList.2.txt
mv xac affectedGeneList.3.txt
mv xad affectedGeneList.4.txt
mv xae affectedGeneList.5.txt
mv xaf affectedGeneList.6.txt
mv xag affectedGeneList.7.txt
mv xah affectedGeneList.8.txt
mv xai affectedGeneList.9.txt
mv xaj affectedGeneList.10.txt
mv xak affectedGeneList.11.txt
mv xal affectedGeneList.12.txt
mv xam affectedGeneList.13.txt
mv xan affectedGeneList.14.txt
mv xao affectedGeneList.15.txt
mv xap affectedGeneList.16.txt
mv xaq affectedGeneList.17.txt
mv xar affectedGeneList.18.txt
mv xas affectedGeneList.19.txt
mv xat affectedGeneList.20.txt
mv xau affectedGeneList.21.txt
mv xav affectedGeneList.22.txt
mv xaw affectedGeneList.23.txt
mv xax affectedGeneList.24.txt
mv xay affectedGeneList.25.txt
mv xaz affectedGeneList.26.txt
mv xba affectedGeneList.27.txt
mv xbb affectedGeneList.28.txt
mv xbc affectedGeneList.29.txt
mv xbd affectedGeneList.30.txt
mv xbe affectedGeneList.31.txt
mv xbf affectedGeneList.32.txt
mv xbg affectedGeneList.33.txt
mv xbh affectedGeneList.34.txt
mv xbi affectedGeneList.35.txt
mv xbj affectedGeneList.36.txt
mv xbk affectedGeneList.37.txt
mv xbl affectedGeneList.38.txt
mv xbm affectedGeneList.39.txt
mv xbn affectedGeneList.40.txt
mv xbo affectedGeneList.41.txt
mv xbp affectedGeneList.42.txt
mv xbq affectedGeneList.43.txt
mv xbr affectedGeneList.44.txt
mv xbs affectedGeneList.45.txt
mv xbt affectedGeneList.46.txt
mv xbu affectedGeneList.47.txt
mv xbv affectedGeneList.48.txt
mv xbw affectedGeneList.49.txt
mv xbx affectedGeneList.50.txt
mv xby affectedGeneList.51.txt
mv xbz affectedGeneList.52.txt
mv xca affectedGeneList.53.txt
mv xcb affectedGeneList.54.txt
mv xcc affectedGeneList.55.txt
mv xcd affectedGeneList.56.txt
mv xce affectedGeneList.57.txt
mv xcf affectedGeneList.58.txt
mv xcg affectedGeneList.59.txt
mv xch affectedGeneList.60.txt
mv xci affectedGeneList.61.txt
mv xcj affectedGeneList.62.txt
mv xck affectedGeneList.63.txt
mv xcl affectedGeneList.64.txt
mv xcm affectedGeneList.65.txt
mv xcn affectedGeneList.66.txt
mv xco affectedGeneList.67.txt
mv xcp affectedGeneList.68.txt
mv xcq affectedGeneList.69.txt
mv xcr affectedGeneList.70.txt
mv xcs affectedGeneList.71.txt
mv xct affectedGeneList.72.txt
mv xcu affectedGeneList.73.txt
mv xcv affectedGeneList.74.txt
mv xcw affectedGeneList.75.txt
mv xcx affectedGeneList.76.txt
mv xcy affectedGeneList.77.txt
mv xcz affectedGeneList.78.txt
mv xda affectedGeneList.79.txt
mv xdb affectedGeneList.80.txt
mv xdc affectedGeneList.81.txt
mv xdd affectedGeneList.82.txt
mv xde affectedGeneList.83.txt
mv xdf affectedGeneList.84.txt
mv xdg affectedGeneList.85.txt
mv xdh affectedGeneList.86.txt
mv xdi affectedGeneList.87.txt
mv xdj affectedGeneList.88.txt
mv xdk affectedGeneList.89.txt
mv xdl affectedGeneList.90.txt
mv xdm affectedGeneList.91.txt
mv xdn affectedGeneList.92.txt
mv xdo affectedGeneList.93.txt
mv xdp affectedGeneList.94.txt
mv xdq affectedGeneList.95.txt
mv xdr affectedGeneList.96.txt
mv xds affectedGeneList.97.txt
mv xdt affectedGeneList.98.txt
mv xdu affectedGeneList.99.txt
mv xdv affectedGeneList.100.txt
mv xdw affectedGeneList.101.txt
mv xdx affectedGeneList.102.txt
mv xdy affectedGeneList.103.txt
mv xdz affectedGeneList.104.txt
mv xea affectedGeneList.105.txt
mv xeb affectedGeneList.106.txt
mv xec affectedGeneList.107.txt
mv xed affectedGeneList.108.txt
mv xee affectedGeneList.109.txt
mv xef affectedGeneList.110.txt
mv xeg affectedGeneList.111.txt
mv xeh affectedGeneList.112.txt
mv xei affectedGeneList.113.txt
mv xej affectedGeneList.114.txt
mv xek affectedGeneList.115.txt
mv xel affectedGeneList.116.txt
mv xem affectedGeneList.117.txt
mv xen affectedGeneList.118.txt
mv xeo affectedGeneList.119.txt
mv xep affectedGeneList.120.txt
mv xeq affectedGeneList.121.txt
mv xer affectedGeneList.122.txt
mv xes affectedGeneList.123.txt
mv xet affectedGeneList.124.txt
mv xeu affectedGeneList.125.txt
mv xev affectedGeneList.126.txt
mv xew affectedGeneList.127.txt
mv xex affectedGeneList.128.txt
mv xey affectedGeneList.129.txt
mv xez affectedGeneList.130.txt
mv xfa affectedGeneList.131.txt
mv xfb affectedGeneList.132.txt
mv xfc affectedGeneList.133.txt
mv xfd affectedGeneList.134.txt
mv xfe affectedGeneList.135.txt
mv xff affectedGeneList.136.txt
mv xfg affectedGeneList.137.txt
mv xfh affectedGeneList.138.txt
mv xfi affectedGeneList.139.txt
mv xfj affectedGeneList.140.txt
mv xfk affectedGeneList.141.txt
mv xfl affectedGeneList.142.txt
mv xfm affectedGeneList.143.txt
mv xfn affectedGeneList.144.txt
mv xfo affectedGeneList.145.txt
mv xfp affectedGeneList.146.txt
mv xfq affectedGeneList.147.txt
mv xfr affectedGeneList.148.txt
mv xfs affectedGeneList.149.txt
mv xft affectedGeneList.150.txt
mv xfu affectedGeneList.151.txt
mv xfv affectedGeneList.152.txt
mv xfw affectedGeneList.153.txt
mv xfx affectedGeneList.154.txt
mv xfy affectedGeneList.155.txt
mv xfz affectedGeneList.156.txt
mv xga affectedGeneList.157.txt
mv xgb affectedGeneList.158.txt
mv xgc affectedGeneList.159.txt
mv xgd affectedGeneList.160.txt
mv xge affectedGeneList.161.txt
mv xgf affectedGeneList.162.txt
mv xgg affectedGeneList.163.txt
mv xgh affectedGeneList.164.txt
mv xgi affectedGeneList.165.txt
mv xgj affectedGeneList.166.txt
mv xgk affectedGeneList.167.txt
mv xgl affectedGeneList.168.txt
mv xgm affectedGeneList.169.txt
mv xgn affectedGeneList.170.txt
mv xgo affectedGeneList.171.txt
mv xgp affectedGeneList.172.txt
mv xgq affectedGeneList.173.txt
mv xgr affectedGeneList.174.txt
mv xgs affectedGeneList.175.txt
mv xgt affectedGeneList.176.txt
mv xgu affectedGeneList.177.txt
mv xgv affectedGeneList.178.txt
mv xgw affectedGeneList.179.txt
mv xgx affectedGeneList.180.txt
mv xgy affectedGeneList.181.txt
mv xgz affectedGeneList.182.txt
mv xha affectedGeneList.183.txt
mv xhb affectedGeneList.184.txt
mv xhc affectedGeneList.185.txt
mv xhd affectedGeneList.186.txt
mv xhe affectedGeneList.187.txt
mv xhf affectedGeneList.188.txt
mv xhg affectedGeneList.189.txt
mv xhh affectedGeneList.190.txt
mv xhi affectedGeneList.191.txt
mv xhj affectedGeneList.192.txt
mv xhk affectedGeneList.193.txt
mv xhl affectedGeneList.194.txt
mv xhm affectedGeneList.195.txt
mv xhn affectedGeneList.196.txt
mv xho affectedGeneList.197.txt
mv xhp affectedGeneList.198.txt
mv xhq affectedGeneList.199.txt
mv xhr affectedGeneList.200.txt
mv xhs affectedGeneList.201.txt
mv xht affectedGeneList.202.txt
mv xhu affectedGeneList.203.txt
mv xhv affectedGeneList.204.txt
mv xhw affectedGeneList.205.txt
mv xhx affectedGeneList.206.txt
mv xhy affectedGeneList.207.txt
mv xhz affectedGeneList.208.txt
mv xia affectedGeneList.209.txt
mv xib affectedGeneList.210.txt
mv xic affectedGeneList.211.txt
mv xid affectedGeneList.212.txt
mv xie affectedGeneList.213.txt
mv xif affectedGeneList.214.txt
mv xig affectedGeneList.215.txt
mv xih affectedGeneList.216.txt
mv xii affectedGeneList.217.txt
mv xij affectedGeneList.218.txt
mv xik affectedGeneList.219.txt
mv xil affectedGeneList.220.txt
